// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Background styles the app window background.
 */
export interface Background {
    /**
     * Color is the background color as a "#RRGGBB" hex string.
     */
    "color": string;

    /**
     * Opacity is the background opacity from 0 (fully transparent) to 1
     * (fully opaque).
     */
    "opacity": number;
}

/**
 * Config is the full persisted configuration.
 */
export interface Config {
    /**
     * Symbols is the ordered list of tracked tickers/indexes (e.g. "AAPL", "^GSPC").
     */
    "symbols": string[] | null;

    /**
     * DefaultRange is the range the app opens with.
     */
    "defaultRange": model$0.Range;

    /**
     * Layout and FormFactor control presentation.
     */
    "layout": Layout;
    "formFactor": FormFactor;

    /**
     * RefreshInterval controls live-tick polling cadence for the 1D view.
     */
    "refreshInterval": time$0.Duration;

    /**
     * Background styles the app window background.
     */
    "background": Background;

    /**
     * Logging configures the leveled, rotating file logger.
     */
    "logging": Logging;
}

/**
 * FormFactor selects the window style. v1 ships Window; Widget (always-on-top)
 * is architected-for and added later.
 */
export enum FormFactor {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FormFactorWindow = "window",
    FormFactorWidget = "widget",
};

/**
 * Layout selects how tracked symbols are arranged. v1 ships Grid; ListDetail is
 * architected-for and added later.
 */
export enum Layout {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LayoutGrid = "grid",
    LayoutListDetail = "list-detail",
};

/**
 * LogLevel controls logging verbosity, ordered from silent (no output at all)
 * to debug (most verbose).
 */
export enum LogLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogSilent = "silent",
    LogError = "error",
    LogWarn = "warn",
    LogInfo = "info",
    LogDebug = "debug",
};

/**
 * Logging is the logger configuration. It is part of Config, so it is persisted
 * and live-reloaded like every other setting.
 */
export interface Logging {
    /**
     * Level is the verbosity, from LogSilent to LogDebug.
     */
    "level": LogLevel;

    /**
     * File is the log file path. Empty means DefaultLogPath().
     */
    "file": string;

    /**
     * MaxSizeMB is the size threshold (in MB) at which the log file is rotated.
     * Zero or negative disables rotation.
     */
    "maxSizeMB": number;

    /**
     * MaxArchives is how many rotated archive files to retain. Zero keeps none
     * (the log simply starts fresh when the threshold is hit).
     */
    "maxArchives": number;
}
