// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Market serves price history and symbol search to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * History returns the price series for a symbol over the given range.
 */
export function History($symbol: string, rng: model$0.Range): $CancellablePromise<model$0.Series> {
    return $Call.ByID(3359389213, $symbol, rng);
}

/**
 * Search returns instruments matching a free-text query (name or symbol).
 */
export function Search(query: string): $CancellablePromise<model$0.SearchResult[] | null> {
    return $Call.ByID(2699213339, query);
}
