// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * UISettings carries the fields editable in the settings view. The frontend
 * validates and submits them as one unit; the tracked-symbol list is managed
 * separately (Add/Remove/MoveSymbol).
 */
export interface UISettings {
    "defaultRange": model$0.Range;
    "refreshSeconds": number;
    "background": config$0.Background;
    "logging": config$0.Logging;
}
