// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings exposes the persisted configuration to the frontend. Mutations go
 * through the config store, so they persist and notify subscribers (main
 * forwards those notifications to the frontend as events).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * AddSymbol appends a symbol to the tracked list, ignoring duplicates.
 */
export function AddSymbol($symbol: string): $CancellablePromise<void> {
    return $Call.ByID(1276670043, $symbol);
}

/**
 * Get returns a snapshot of the current configuration.
 */
export function Get(): $CancellablePromise<config$0.Config> {
    return $Call.ByID(2117494788);
}

/**
 * MoveSymbol swaps the symbol at index with its neighbor delta positions away
 * (delta is -1 or +1), persisting the new order. Out-of-range moves are no-ops.
 */
export function MoveSymbol(index: number, delta: number): $CancellablePromise<void> {
    return $Call.ByID(2593978513, index, delta);
}

/**
 * RemoveSymbol drops a symbol from the tracked list.
 */
export function RemoveSymbol($symbol: string): $CancellablePromise<void> {
    return $Call.ByID(1797664500, $symbol);
}
