// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as config$0 from "../../../../MarioStoilov/simplestonks/internal/config/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "configChanged": config$0.Config;
        }
    }
}
