// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Candle is a single OHLC data point in a price series.
 */
export interface Candle {
    "Time": string;
    "Open": number;
    "High": number;
    "Low": number;
    "Close": number;
    "Volume": number;
}

/**
 * Range is a selectable chart time range, mirroring the Yahoo Finance toggles.
 */
export enum Range {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * intraday, live-ticking default view
     */
    Range1D = "1D",

    /**
     * trading week
     */
    Range5D = "5D",

    /**
     * calendar week
     */
    Range1W = "1W",

    /**
     * one month
     */
    Range1M = "1M",

    /**
     * year to date
     */
    RangeYTD = "YTD",

    /**
     * one year
     */
    Range1Y = "1Y",

    /**
     * five years
     */
    Range5Y = "5Y",

    /**
     * full available history
     */
    RangeAll = "ALL",
};

/**
 * SearchResult is one instrument returned by a symbol search: enough to show
 * the user a disambiguated suggestion (symbol, full name, market/exchange).
 */
export interface SearchResult {
    /**
     * e.g. "AAPL", "^GSPC"
     */
    "Symbol": string;

    /**
     * full/long name, e.g. "Apple Inc."
     */
    "Name": string;

    /**
     * market/exchange display, e.g. "NASDAQ"
     */
    "Exchange": string;

    /**
     * instrument type, e.g. "Equity", "Index", "ETF"
     */
    "Type": string;
}

/**
 * Series is a symbol's price history over a requested range, plus enough
 * metadata to render the current price and percent change.
 */
export interface Series {
    "Symbol": string;

    /**
     * friendly display name, e.g. "S&P 500"; may be empty
     */
    "Name": string;
    "Range": Range;
    "Currency": string;
    "Candles": Candle[] | null;

    /**
     * reference close used for the range's % change
     */
    "PreviousClose": number;

    /**
     * SessionStart/SessionEnd bound the regular trading session the series
     * belongs to (when the provider knows it). An intraday chart is drawn
     * against this full window so a live day fills in gradually.
     */
    "SessionStart": string;
    "SessionEnd": string;
}
